# headers and icon 
title: Ye Yan Gu
info: MS ai @ nycu
icon-pic: assets/img/Blink2.gif

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
